# Generated by Django 4.2.5 on 2023-10-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualEntrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrepreneur_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ИП')),
                ('contact_email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='email ИП')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='адрес')),
            ],
            options={
                'verbose_name': 'индивидуальный предприниматель',
                'verbose_name_plural': 'индивидуальные предприниматели',
                'ordering': ('country', 'city'),
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Производитель')),
                ('contact_email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='email производителя')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='адрес')),
            ],
            options={
                'verbose_name': 'производитель',
                'verbose_name_plural': 'производители',
                'ordering': ('country', 'city'),
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suppliers_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Поставщик')),
                ('contact_email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='email поставщика')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='адрес')),
            ],
            options={
                'verbose_name': 'поставщик',
                'verbose_name_plural': 'поставщики',
                'ordering': ('country', 'city'),
            },
        ),
    ]
