# Generated by Django 4.2.5 on 2023-10-10 15:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_manufacturer_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ('country', 'city', 'status'), 'verbose_name': 'компания', 'verbose_name_plural': 'компании'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ('product_name', 'release_date', 'create_date'), 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AddField(
            model_name='orders',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 10, 18, 36, 17, 154540), verbose_name='дата создания'),
        ),
        migrations.AddField(
            model_name='orders',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='задолжность'),
        ),
        migrations.AddField(
            model_name='orders',
            name='product_model',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='модель'),
        ),
        migrations.AddField(
            model_name='orders',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='продукт'),
        ),
        migrations.AddField(
            model_name='orders',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 10, 18, 36, 17, 154540), verbose_name='дата выхода продукта на рынок'),
        ),
        migrations.AddField(
            model_name='orders',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.manufacturer', verbose_name='поставщик'),
        ),
    ]
