# Generated by Django 4.2.5 on 2023-10-10 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_orders_create_date_alter_orders_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 10, 20, 45, 17, 486046), verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 10, 20, 45, 17, 486046), verbose_name='дата выхода продукта на рынок'),
        ),
    ]
