# Generated by Django 4.2.5 on 2023-10-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_orders_create_date_alter_orders_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='release_date',
            field=models.DateField(verbose_name='дата выхода продукта на рынок'),
        ),
    ]
